apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customresources.cache.example.com
spec:
  group: cache.example.com
  names:
    kind: CustomResource
    listKind: CustomResourceList
    plural: customresources
    singular: customresource
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CustomResource is the Schema for the customresources API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CustomResourceSpec defines the desired state of CustomResource
          properties:
            size:
              description: Size of the Deployment
              format: int32
              type: integer
          required:
          - size
          type: object
        status:
          description: CustomResourceStatus defines the observed state of CustomResource
          properties:
            nodes:
              description: Nodes are the names of the CustomResource pods... ?? to
                check
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
