# Copyright (c) 2020 Swisscom Blockchain AG
# Licensed under MIT License
apiVersion: polkadot.swisscomblockchain.com/v1alpha1
kind: Polkadot
metadata:
  name: polkadot-cr
spec:
  clientVersion: latest
  kind: "SentryAndValidator"
  isNetworkPolicyActive: "false"
  isDataPersistenceActive: "false" # TODO dataPersistence: move into sentry and validator
  isMetricsSupportActive: "false" # TODO metrics: -> enabled:true
  sentry:
    replicas: 1
    clientName: "IronoaSentry"
    nodeKey: "0000000000000000000000000000000000000000000000000000000000000013" # Local node id: QmQMTLWkNwGf7P5MQv7kUHCynMg7jje6h3vbvwd2ALPPhm
    reservedValidatorID: "QmQtR1cdEaJM11qBWQBd34FoSgFichCjhtsBfrUFsVAjZM"
    # TODO ResourceRequirements definition, more granular
    CPULimit: "1"
    memoryLimit: "1Gi"
    ##############
    # TODO dataPersistence: enabled, storageClassName, ...
    storageClassName: "default" #["default","managed-premium"]
  validator:
    clientName: "IronoaValidator"
    nodeKey: "0000000000000000000000000000000000000000000000000000000000000021" # Local node id: QmQtR1cdEaJM11qBWQBd34FoSgFichCjhtsBfrUFsVAjZM
    reservedSentryID: "QmQMTLWkNwGf7P5MQv7kUHCynMg7jje6h3vbvwd2ALPPhm"
    CPULimit: "1"
    memoryLimit: "1Gi"
    storageClassName: "default" #["default","managed-premium"]
