apiVersion: apps/v1
kind: Deployment
metadata:
  name: customresource-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: customresource-operator
  template:
    metadata:
      labels:
        name: customresource-operator
    spec:
      serviceAccountName: customresource-operator
      containers:
        - name: customresource-operator
          image: ironoa/customresource-operator:v0.0.5
          command:
          - customresource-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "customresource-operator"
